config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  authenticate :user do
    get   '/users/admin',           to: 'users/admin#index',  as: 'list_users'
    get   '/users/admin/:id',       to: 'users/admin#show',   as: 'show_user'
    get   '/users/admin/:id/edit',  to: 'users/admin#edit',   as: 'edit_user'
    patch '/users/admin/:id',       to: 'users/admin#update', as: 'user'

    get   '/houses/:id/detail', to: 'houses#detail', as: 'house_detail'
    get   '/people/:id/detail', to: 'people#detail', as: 'person_detail'
    get   '/people/occupant/:house_id', to: 'people#new_occupant', as: 'new_occupant'
    get   '/non_occupants', to: 'non_occupants#index', as: 'non_occupants'
    patch '/non_occupant/:id', to: 'non_occupants#update', as: 'non_occupant'
    resources :addresses, :phones, :emails, :people,
              :person_phones, :person_addresses,
              :houses, :ownerships, :contributions,
              :positions
    root 'welcome#home', as: :root
  end

  unauthenticated do
    devise_scope :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/controllers/non_occupants_controller.rb
# frozen_string_literal: true

class NonOccupantsController < ApplicationController
  def index
    @q = non_occup_query
    @pagy, @non_occupants = pagy(@q.result)
    @house_id = params.dig(:q,:house_id) || params.dig(:house_id)
  end

  def update
    redirect_to houses_path and return unless house_id
    non_occupant = Person.find(params[:id])
    if non_occupant.update(house_id: house_id)
      redirect_to house_detail_path(id: house_id), notice: 'An occupant was added.'
    else
      render :index
    end
  end

  private

  def non_occup_query
    Person
      .where(house_id: nil)
      .order(last: :asc, first: :asc, middle: :asc)
      .ransack(params[:q])
  end

  def house_id
    @house_id ||= existing_house_id
  end

  def existing_house_id
    House.find(house_id_as_UUID_from_params).id
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def house_id_as_UUID_from_params
    params[:house_id].match(SharedRegexp::UUID_FORMAT)[0]
  end
end

app/views/non_occupants/_search_form.html.erb
<%= search_form_for @q, url: non_occupants_url do |f| %>
  <%= f.hidden_field :house_id, value: @house_id %>

  <div class="row">
    <div class="col-sm-5">
      <%= f.label :last_cont %>
      <%= f.search_field :last_cont %>
    </div>

    <div class="col-sm-2">
      <%= f.submit %>
    </div>

    <div class="col">
      <%= link_to "Clear", non_occupants_path(house_id: @house_id) %>
    </div>
  </div>

<% end %>

app/views/non_occupants/index.html.erb
<p id="notice"><%= notice %></p>

<% present(nil, NonOccupantsPresenter) do |non_occupant| %>
  <h1>Occupant Candidates</h1>
  <h2>for <%= non_occupant.topic_house(@house_id) %></h2>
<% end %>
<br>

<%= render partial:'search_form', locals: {house_id: @house_id} %>
<br>

<table class='table table-sm table-bordered table-hover', id='people'>
  <thead class='thead-light'>
    <tr>
      <th>Nickname</th>
      <th>Name</th>
      <th>Role</th>
      <th>Status</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
    <% @non_occupants.each do |n| %>
      <% present(n) do |person| %>
        <tr>
          <td><%= person.nickname %></td>
          <td><%= person.sortable_name %></td>
          <td><%= person.role %></td>
          <td><%= person.status %></td>
          <td><%= link_to 'Add to House', non_occupant_path(person.id, {house_id: @house_id}), method: :patch %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%== pagy_bootstrap_nav(@pagy) %>

<%= link_to 'House Detail', house_detail_path(id: @house_id) %>