config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  authenticate :user do
    get   '/users/admin',           to: 'users/admin#index',  as: 'list_users'
    get   '/users/admin/:id',       to: 'users/admin#show',   as: 'show_user'
    get   '/users/admin/:id/edit',  to: 'users/admin#edit',   as: 'edit_user'
    patch '/users/admin/:id',       to: 'users/admin#update', as: 'user'

    get   '/houses/:id/detail', to: 'houses#detail', as: 'house_detail'
    get   '/people/:id/detail', to: 'people#detail', as: 'person_detail'
    get   '/people/occupant/:house_id', to: 'people#new_occupant', as: 'new_occupant'
    get   '/non_occupants', to: 'non_occupants#index', as: 'non_occupants'
    patch '/non_occupant/:id', to: 'non_occupants#update', as: 'non_occupant'
    resources :addresses, :phones, :emails, :people,
              :person_phones, :person_addresses,
              :houses, :ownerships, :contributions,
              :positions
    root 'welcome#home', as: :root
  end

  unauthenticated do
    devise_scope :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  has_many :addresses, -> { order(state: :asc, city: :asc, street: :asc, number: :asc) }
  has_many :emails, -> { order(addr: :asc) }
  has_many :phones, -> { order(cc: :asc, area: :asc, prefix: :asc, number: :asc) }
  belongs_to :house, optional: true
  has_many :ownerships
  has_many :properties, through: :ownerships
  has_many :positions

  validates :first, presence: true
  validates :last,  presence: true

  delegate  :fullname, :sortable_name, :informal_name, :formal_name,
            to: :person_name

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "first", "honorific", "house_id", "id", "last", "middle", "nickname", "note", "pref_address_id", "pref_email_id", "pref_phone_id", "role", "status", "suffix", "updated_at"]
  end

  # Should this move to PersonPresenter?
  def person_name
    PersonName.new(first, middle, last, nickname, suffix, honorific)
  end

  def person_name=(person_name)
    self.nickname = person_name.nickname
    self.first = person_name.first
    self.middle = person_name.middle
    self.last = person_name.last
    self.suffix = person_name.suffix
    self.honorific = person_name.honorific
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  before_action :set_person, only: %i[show detail edit update destroy]

  # GET /people
  def index
    @q = Person.includes(:house)
               .order(last: :asc, first: :asc, middle: :asc)
               .ransack(params[:q])
    @pagy, @people = pagy(@q.result)
  end

  # GET /people/1
  def show; end

  # GET /people/1/detail
  def detail; end

  # GET /people/new
  def new
    @person = Person.new
    @disable_house_select = false
  end

  # GET /people/occupant/<house_id>
  def new_occupant
    redirect_to houses_path and return unless house_id
    @person = Person.new(house_id: house_id)
    @disable_house_select = true
  end

  # GET /people/1/edit
  def edit
    @disable_house_select = false
  end

  # POST /people
  def create
    @person = Person.create(person_params)
    if @person.save
      redirect_to @person, notice: 'Person was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /people/1
  def update
    if @person.update(person_params)
      redirect_to @person, notice: 'Person was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy
    redirect_to people_url, notice: 'Person was successfully destroyed.'
  end

  private

  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:nickname, :first, :middle, :last, :suffix, :honorific,
                                   :note, :house_id, :role, :status)
  end

  def house_id
    @house_id ||= existing_house_id
  end

  def existing_house_id
    House.find(house_id_as_UUID_from_params).id
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def house_id_as_UUID_from_params
    params[:house_id].match(SharedRegexp::UUID_FORMAT)[0]
  end
end

app/helpers/people_helper.rb
# frozen_string_literal: true

module PeopleHelper
end

app/views/people/_addresses.html.erb
<%= render  partial: 'shared/subtable_header_bs',
            locals: { title: "Addresses:",
                      link_text1: nil,
                      path1: nil,
                      link_text2: nil,
                      path2: nil } %>

<table class='table table-sm table-bordered table-hover', id='addresses'>
  <thead class='thead-light'>
    <tr class='d-flex'>
      <th class='col-3'>Address</th>
      <th class='col-2'>Type</th>
      <th class='col-1'>Pref?</th>
      <th class='col-3'>Note</th>
      <th class='col-3'><%= link_to 'New Address', new_address_path(person_id: person.id) %></th>
    </tr>
  </thead>

  <tbody>
    <% person.addresses.each do |a| %>
      <% present(a) do |address| %>
        <tr class='d-flex'>
          <td class='col-3'><%= address.address %></td>
          <td class='col-2'><%= address.address_type %></td>
          <td class='col-1'><%= address.primary %></td>
          <td class='col-3'><%= address.note %></td>
          <td class='col-1'><%= link_to 'Show', address %></td>
          <td class='col-1'><%= link_to 'Edit', edit_address_path(address) %></td>
          <td class='col-1'><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/people/_emails.html.erb
<%= render  partial: 'shared/subtable_header_bs',
            locals: { title: "Emails:",
                      link_text1: nil,
                      path1: nil,
                      link_text2: nil,
                      path2: nil } %>

<table class='table table-sm table-bordered table-hover', id='emails'>
  <thead class='thead-light'>
    <tr class='d-flex'>
      <th class='col-3'>Email</th>
      <th class='col-2'>Type</th>
      <th class='col-1'>Pref?</th>
      <th class='col-3'>Note</th>                    
      <th class='col-3'><%= link_to 'New Email', new_email_path(person_id: person.id) %></th>
    </tr>
  </thead>

  <tbody>
    <% person.emails.each do |e| %>
      <% present(e) do |email| %>
        <tr class='d-flex'>
          <td class='col-3'><%= email.addr %></td>
          <td class='col-2'><%= email.email_type %></td>
          <td class='col-1'><%= email.primary %></td>
          <td class='col-3'><%= email.note %></td>
          <td class='col-1'><%= link_to 'Show', email %></td>
          <td class='col-1'><%= link_to 'Edit', edit_email_path(email) %></td>
          <td class='col-1'><%= link_to 'Destroy', email, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% present(person) do |person| %>
    <%  person.form = form %>
    <%= person.show_errors %>

    <%= person.input_row( [ { attribute: :nickname } ] ) %>

    <%= person.input_row( [ { attribute: :first },
                            { attribute: :middle },
                            { attribute: :last }      ] ) %>

    <%= person.input_row( [ { attribute: :suffix },
                            { attribute: :honorific } ] ) %>


    <%= person.input_row( [ {attribute: :house_id, kind: :select,
                             collection: person.houses,
                             blank: true,
                             selected: person.house_id,
                             disabled: @disable_house_select },
                           { attribute: :role, kind: :select,
                             collection: person.roles,
                             selected: person.role || "Unknown" },
                           { attribute: :status, kind: :select,
                             collection: person.statuses,
                             selected: person.role || "Unknown" } ] ) %>

    <%= person.input_row([ { attribute: :note, kind: :textarea } ] ) %>

    <%= render  partial: 'shared/form_submit_bs',
                locals: { form: form , my_label: nil } %>
  <% end %>
<% end %>

app/views/people/_phones.html.erb
<%= render  partial: 'shared/subtable_header_bs',
            locals: { title: "Phones:",
                      link_text1: nil,
                      path1: nil,
                      link_text2: nil,
                      path2: nil } %>

<table class='table table-sm table-bordered table-hover', id='phones'>
  <thead class='thead-light'>
    <tr class='d-flex'>
      <th class='col-3'>Phone</th>
      <th class='col-2'>Type</th>
      <th class='col-1'>Pref?</th>
      <th class='col-1'>Msgs?</th>
      <th class='col-2'>Note</th>
      <th class='col-3'><%= link_to 'New Phone', new_phone_path(person_id: person.id) %></th>
    </tr>
    </tr>
  </thead>

  <tbody>
    <% person.phones.each do |p| %>
      <% present(p) do |phone| %>
        <tr class='d-flex'>
          <td class='col-3'><%= phone.ph_number %></td>
          <td class='col-2'><%= phone.phone_type %></td>
          <td class='col-1'><%= phone.primary %></td>
          <td class='col-1'><%= phone.txt_capable %></td>
          <td class='col-2'><%= phone.note %></td>
          <td class='col-1'><%= link_to 'Show', phone %></td>
          <td class='col-1'><%= link_to 'Edit', edit_phone_path(phone) %></td>
          <td class='col-1'><%= link_to 'Destroy', phone, method: :delete, data: { confirm: 'Are you sure?'} %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/people/_search_form.html.erb
<%= search_form_for @q do |f| %>
  <div class="row">
    <div class="col-sm-5">
      <%= f.label :last_cont %>
      <%= f.search_field :last_cont %>
    </div>

    <div class="col-sm-3">
      <%= f.check_box :house_id_blank %>
      <%= f.label :house_id_blank, "House is Blank" %>
    </div>

    <div class="col-sm-2">
      <%= f.submit %>
    </div>

    <div class="col">
      <%= link_to "Clear", people_path, method: :get %>
    </div>
  </div>
<% end %>

app/views/people/detail.html.erb
<% present(@person) do |person| %>

  <h1><%= person.formal_name %></h1> 

  <%= person.show_row do %>
    <%= person.show :house_address, 'center', 'House', 4    %>
    <%= person.show :nickname %>
    <%= person.show :role      %>
  <% end %>

  <%= person.show_row do %>
    <%= person.show :status                       %>
    <%= person.show :current_position, 'center', 'Position' %>
  <% end %>

  <div class="row">
    <div class="col-sm-12">
      <h5 class="bg-light font-weight-bolder">Preferred:</h5>
    </div>
  </div>

  <%= person.show_row do %>
    <%= person.show :preferred_email,'center', 'Email', 3  %>
    <%= person.show :preferred_phone,'center', 'Phone', 3  %>
    <%= person.show :preferred_address,'center', 'Address' %>
  <% end %>

  <div class="row">
    <div class="col-sm">
      <%= render 'emails', person: @person %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm">
      <%= render 'phones', person: @person %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm">
      <%= render 'addresses', person: @person %>
    </div>
  </div>

  <%= person.show_row do %>
    <%= person.show :note %>
  <% end %>
    
<% end %>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'List', people_path %>

app/views/people/edit.html.erb
<h1>Edit Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Person Detail', person_detail_path(@person) %> |
<%= link_to 'List', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<%= render 'search_form' %>
<br>

<table class='table table-sm table-bordered table-hover', id='people'>
  <thead class='thead-light'>
    <tr>
      <th>Nickname</th>
      <th>Name</th>
      <th>Suffix</th>
      <th>Honorific</th>
      <th>House</th>
      <th>Role</th>
      <th>Status</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |p| %>
      <% present(p) do |person| %>
        <tr>
          <td><%= person.nickname %></td>
          <td><%= person.sortable_name %></td>
          <td><%= person.suffix %></td>
          <td><%= person.honorific %></td>
          <td><%= person.house_id ? person.house_address : '' %></td>
          <td><%= person.role %></td>
          <td><%= person.status %></td>
          <td><%= person.note %></td>
          <td><%= link_to 'Detail', person_detail_path(person) %></td>
          <td><%= link_to 'Edit', edit_person_path(person) %></td>
          <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%== pagy_bootstrap_nav(@pagy) %>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'List', people_path %>

app/views/people/new_occupant.html.erb
<h1>New Occupant</h1>

<%= render 'form', person: @person %>

<%= link_to 'List', people_path %>

app/views/people/show.html.erb
<h1>Person</h1>

<% present(@person) do |person| %>
	<%= person.notice(notice) %>

	<%= person.show(:nickname) %>
	<%= person.show(:first) %>
	<%= person.show(:middle) %>
	<%= person.show(:last) %>
	<%= person.show(:suffix) %>
	<%= person.show(:honorific) %>
	<%= person.show(:note) %>
	<%= person.show(:house_address, 'House') %>
	<%= person.show(:role) %>
	<%= person.show(:status) %>
<% end %>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Person Detail', person_detail_path(@person) %> |
<%= link_to 'List', people_path %>