config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  authenticate :user do
    get   '/users/admin',           to: 'users/admin#index',  as: 'list_users'
    get   '/users/admin/:id',       to: 'users/admin#show',   as: 'show_user'
    get   '/users/admin/:id/edit',  to: 'users/admin#edit',   as: 'edit_user'
    patch '/users/admin/:id',       to: 'users/admin#update', as: 'user'

    get   '/houses/:id/detail', to: 'houses#detail', as: 'house_detail'
    get   '/people/:id/detail', to: 'people#detail', as: 'person_detail'
    get   '/people/occupant/:house_id', to: 'people#new_occupant', as: 'new_occupant'
    get   '/non_occupants', to: 'non_occupants#index', as: 'non_occupants'
    patch '/non_occupant/:id', to: 'non_occupants#update', as: 'non_occupant'
    resources :addresses, :phones, :emails, :people,
              :person_phones, :person_addresses,
              :houses, :ownerships, :contributions,
              :positions
    root 'welcome#home', as: :root
  end

  unauthenticated do
    devise_scope :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/house.rb
# frozen_string_literal: true

class House < ApplicationRecord
  include Comparable

  has_many :occupants,
           -> { order(last: :asc, first: :asc, middle: :asc) },
           class_name: 'Person'
  has_many :ownerships
  has_many :owners,
           -> { order(last: :asc, first: :asc, middle: :asc) },
           through: :ownerships
  has_many :contributions,
           -> { order(date_paid: :asc) }
  has_many :links
  has_many :lots, through: :links

  validate :lat_is_sane
  validate :lng_is_sane

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "current_dues", "flag", "id", "image_link", "lat", "listed", "lng", "note", "number", "rental", "status", "street", "updated_at"]
  end

  def <=>(other)
    return -1 if street < other.street
    return +1 if street > other.street

    number <=> other.number
  end

  private

  def lat_is_sane
    return unless lat

    if lat > 90
      errors.add(:lat, 'is > 90 deg')
    elsif lat < -90
      errors.add(:lat, 'is < -90 deg')
    end
  end

  def lng_is_sane
    return unless lng

    if lng > 180
      errors.add(:lng, 'is > 180 deg')
    elsif lng < -180
      errors.add(:lng, 'is < -180 deg')
    end
  end
end

app/controllers/houses_controller.rb
# frozen_string_literal: true

class HousesController < ApplicationController
  before_action :set_house, only: %i[show detail edit update destroy]

  # GET /houses
  def index
    @q = House.includes(:lots).ransack(params[:q])
    @q.sorts = ['street asc', 'number asc'] if @q.sorts.empty?
    @pagy, @houses = pagy(@q.result)
  end

  # GET /houses/1
  def show; end

  # GET /houses/1/detail
  def detail; end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit; end

  # POST /houses
  def create
    @house = House.new(house_params)
    if @house.save
      redirect_to @house, notice: 'House was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /houses/1
  def update
    if @house.update(house_params)
      redirect_to @house, notice: 'House was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /houses/1
  def destroy
    @house.destroy
    redirect_to houses_url, notice: 'House was successfully destroyed.'
  end

  private

  def set_house
    @house = House.find(params[:id])
  end

  def house_params
    params.require(:house).permit(:number, :street, :lat, :lng, :image_link,
                                  :flag, :rental, :listed, :status, :note, lot_ids: [])
  end
end

app/helpers/houses_helper.rb
# frozen_string_literal: true

module HousesHelper
end

app/views/houses/_contributions.html.erb
<%= render  partial: 'shared/subtable_header_bs',
            locals: { title: "Contributions:",
                      link_text1: nil,
                      path1: nil,
                      link_text2: nil,
                      path2: nil } %>

<table class='table table-sm table-bordered table-hover', id='contributions'>
  <thead class='thead-light'>
    <tr>
      <th>Date paid</th>
      <th>Amount</th>
      <th class='col-3'><%= link_to 'New Contribution', new_contribution_path(house_id: house.id) %></th>
    </tr>
  </thead>

  <tbody>
    <% house.contributions.each do |c| %>
      <% present(c) do |contribution| %>
        <tr>
          <td><%= contribution.date_paid %></td>
          <td><%= contribution.amount %></td>
          <td><%= link_to 'Show', contribution %></td>
          <td><%= link_to 'Edit', edit_contribution_path(contribution) %></td>
          <td><%= link_to 'Destroy', contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/houses/_form.html.erb
<%= form_with(model: house, local: true) do |form| %>
  <% present(house) do |house| %>
    <%  house.form = form %>
    <%= house.show_errors %>

    <%= house.input_row([ { attribute: :number},
                          { attribute: :street},
                          { attribute: :status, kind: :select,
                            collection:  house.statuses,
                            selected: house.status || "Occupied" }  ]) %>

    <%= house.input_row([ { attribute: :flag, kind: :checkbox,
                            label: "Member Flag Group" },
                          { attribute: :rental, kind: :checkbox,
                            label: "Rental Property" },
                          { attribute: :listed, kind: :checkbox,
                            label: "For Sale" }                     ]) %>

    <%= house.input_row([ {attribute: :lat},
                          {attribute: :lng},
                          {attribute: :image_link}                  ]) %>

    <%= house.input_row([ { attribute: :lot_ids, kind: :select,
                            label: "Linked Lots",
                            collection: grouped_options_for_select(house.for_select, house.lot_ids),
                            multiple: true,
                            hidden_mirror: false,
                            blank: true,
                            width: 3 },
                          { kind: :textarea, attribute: :note,
                            label: "Notes",
                            width: 6, rows: 3 }                     ]) %>

    <%= render  partial: 'shared/form_submit_bs',
                locals: { form: form } %>
  <% end %>
<% end %>

app/views/houses/_occupants.html.erb
<%= render  partial: 'shared/subtable_header_bs',
            locals: { title: "Occupants:",
                      link_text1: nil,
                      path1: nil,
                      link_text2: nil,
                      path2: nil } %>

<table class='table table-sm table-bordered table-hover'>
  <thead class='thead-light'>
    <% present(house) do |h| %>
    <tr>
      <th>Occupant</th>
      <th>Role</th>
      <th>Status</th>
      <th class='col-2'><%= link_to 'New Person as Occupant', new_occupant_path(house_id: house.id) %></th>
      <th class='col-1'><%= link_to 'Add Occupant', non_occupants_path(house_id: house.id)  %></th>
    </tr>
    <% end %>
  </thead>

  <tbody>
    <% house.occupants.each do |o| %>
      <% present(o) do |occupant| %>
        <tr>
          <td><%= occupant.fullname %></td>
          <td><%= occupant.role %></td>
          <td><%= occupant.status %></td>
          <td><%= link_to 'Show', occupant %></td>
          <td><%= link_to 'Edit', edit_person_path(occupant) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/houses/_owners.html.erb
<%= render  partial: 'shared/subtable_header_bs',
            locals: { title: "Ownerships:",
                      link_text: "New Ownership",
                      path: new_ownership_path(house_id: @house.id) } %>

<table class='table table-sm table-bordered table-hover'>
  <thead class='thead-light'>
    <tr>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @house.ownerships.each do |ownership| %>
      <tr>
        <td><%= ownership.person.fullname %></td>
        <td><%= link_to 'Show', ownership %></td>
        <td><%= link_to 'Edit', edit_ownership_path(ownership) %></td>
        <td><%= link_to 'Destroy', ownership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/houses/_ownerships.html.erb
<%= render  partial: 'shared/subtable_header_bs',
            locals: { title: "Owners:",
                      link_text1: nil,
                      path1: nil,
                      link_text2: nil,
                      path2: nil } %>

<table class='table table-sm table-bordered table-hover'>
  <thead class='thead-light'>
    <tr>
      <th>Owner</th>
      <th class='col-3'><%= link_to 'New Owner', new_ownership_path(house_id: house.id) %></th>
    </tr>
  </thead>

  <tbody>
    <% house.ownerships.each do |o| %>
      <% present(o) do |ownership| %>
        <tr>
          <td><%= ownership.owner_name %></td>
          <td><%= link_to 'Show', ownership %></td>
          <td><%= link_to 'Edit', edit_ownership_path(ownership) %></td>
          <td><%= link_to 'Destroy', ownership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/houses/_search_form.html.erb
<%= search_form_for @q do |f| %>
  <div class='row'>
    <div class="field col-sm-4">
      <%= f.label :flag_eq, 'Flag: ' %>
      <%= f.collection_radio_buttons :flag_eq, {'Yes' => true, 'No' => false, 'All' => nil}, :last, :first %>
    </div>

    <div class="field col-sm-4">
      <%= f.label :rental_eq, 'Rental: ' %>
      <%= f.collection_radio_buttons :rental_eq, {'Yes ' => true, 'No ' => false, 'All ' => nil}, :last, :first %>
    </div>

    <div class="field col-sm-4">
      <%= f.label :listed_eq, 'Listed: ' %>
      <%= f.collection_radio_buttons :listed_eq, {'Yes' => true, 'No' => false, 'All' => nil}, :last, :first %>
    </div>
  </div>

  <div class='row'>
    <div class='field col-sm-3'>
      <%= f.label :street, 'Street: ' %>
      <%= f.select(:street_eq, house.street_names, { include_blank: true }) %>
    </div>

    <div class='field col-sm-4'>
      <%= f.label :number, 'Number: ' %>
      <%= f.text_field(:number_eq) %>
    </div>

    <div class='field col-sm-3'>
      <%= f.label :status, 'Status: ' %>
      <%= f.select(:status_eq, house.statuses, { include_blank: true }) %>
    </div>

    <div class="field col-sm-2">
      <%= f.submit %>
    </div>
  </div>

<% end %>
</br>

app/views/houses/detail.html.erb
<% present(@house) do |house| %>

  <h1><%= house.house_address %></h1>

  <%= house.show_row do %>
    <%= house.show :flag, 'center', 'Member Flag Group' %>
    <%= house.show :rental, 'center', 'Rental Property' %>
    <%= house.show :listed, 'center', 'Listed For Sale' %>
  <% end %>

  <%= house.show_row do %>
    <%= house.show :lat, 'center', 'Latitude' %>
    <%= house.show :lng, 'center', 'Longitude' %>
    <%= house.show :image_link, 'center', 'Image Link' %>
  <% end %>

  <%= house.show_row do %>
    <%= house.show :status %>
    <%= house.show :linked_lot_addresses, 'center', 'Linked Lots' %>
  <% end %>

  <div class="row">
    <div class="col-sm">
      <%= render 'occupants', house: @house %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm">
      <%= render 'contributions', house: @house %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm">
      <%= render 'ownerships', house: @house %>
    </div>
  </div>

  <%= house.show_row do %>
    <%= house.show :note %>
  <% end %>

<% end %>

<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'List', houses_path %>

app/views/houses/edit.html.erb
<h1>Edit House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house %> |
<%= link_to 'House Detail', house_detail_path(@house) %> |
<%= link_to 'List', houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
  <div class="field col-sm-2">
    <h1>Houses</h1>
  </div>
  <div class="field col-sm-8">
    <% present(nil, HousePresenter) do |h| %>
      <%= render 'search_form', house: h %>
    <% end %>
  </div>
</div>

<table class='table table-sm table-bordered table-hover'>
  <thead class='thead-light'>
    <tr>
      <th style="width: 14%"><%= sort_link(@q,:house_address, [:street, :number], 'Address') %></th>
      <th style="width: 8%"><%= sort_link(@q,:flag) %></th>
      <th style="width: 8%"><%= sort_link(@q,:rental) %></th>
      <th style="width: 8%"><%= sort_link(@q,:listed) %></th>
      <th style="width: 8%"><%= sort_link(@q,:status) %></th>
      <th style="width: 16%">Linked Lots</th>
      <th style="width: 16%">Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @houses.each do |h| %>
      <% present(h) do |house| %>
        <tr>
          <td><%= house.house_address %></td>
          <td><%= house.flag %></td>
          <td><%= house.rental %></td>
          <td><%= house.listed %></td>
          <td><%= house.status %></td>
          <td><%= house.linked_lot_addresses %></td>
          <td><%= house.note %></td>
          <td><%= link_to 'Detail', house_detail_path(house) %></td>
          <td><%= link_to 'Edit', edit_house_path(house) %></td>
          <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%== pagy_bootstrap_nav(@pagy) %>
<br>
<%= link_to 'New House', new_house_path %>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form', house: @house %>

<%= link_to 'List', houses_path %>

app/views/houses/show.html.erb
<h1>House</h1>

<% present(@house) do |house| %>
	<%= house.notice(notice) %>

	<%= house.show(:house_address, 'House Address') %>
	<%= house.show(:linked_lot_addresses, 'Linked Lots') %>
	<%= house.show(:lat, 'Latitude') %>
	<%= house.show(:lng, 'Longitude') %>
	<%= house.show(:image_link, 'Image Link') %>
	<%= house.show(:flag, 'Member Flag Group') %>
	<%= house.show(:rental, 'Rental Property') %>
	<%= house.show(:listed, 'Listed For Sale') %>
	<%= house.show(:status, 'Status') %>
	<%= house.show(:note, 'Note') %>
<% end %>

<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'House Detail', house_detail_path(@house) %> |
<%= link_to 'List', houses_path %>