config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  authenticate :user do
    get   '/users/admin',           to: 'users/admin#index',  as: 'list_users'
    get   '/users/admin/:id',       to: 'users/admin#show',   as: 'show_user'
    get   '/users/admin/:id/edit',  to: 'users/admin#edit',   as: 'edit_user'
    patch '/users/admin/:id',       to: 'users/admin#update', as: 'user'

    get   '/houses/:id/detail', to: 'houses#detail', as: 'house_detail'
    get   '/people/:id/detail', to: 'people#detail', as: 'person_detail'
    get   '/people/occupant/:house_id', to: 'people#new_occupant', as: 'new_occupant'
    get   '/non_occupants', to: 'non_occupants#index', as: 'non_occupants'
    patch '/non_occupant/:id', to: 'non_occupants#update', as: 'non_occupant'
    resources :addresses, :phones, :emails, :people,
              :person_phones, :person_addresses,
              :houses, :ownerships, :contributions,
              :positions
    root 'welcome#home', as: :root
  end

  unauthenticated do
    devise_scope :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #:lockable, :timeoutable, :trackable #:confirmable,

  def authenticatable_salt
    "#{super}#{session_token}"
  end

  def invalidate_session!
    update_attribute(:session_token, SecureRandom.hex)
  end

  def std_name
    return email if first_name.blank? && last_name.blank?
    return first_name if !first_name.blank? && last_name.blank?
    return last_name  if first_name.blank? && !last_name.blank?

    "#{first_name} #{last_name}"
  end
end

app/controllers/users/admin_controller.rb
# frozen_string_literal: true

module Users
  class AdminController < ApplicationController
    before_action :set_user, only: %i[show edit update]

    def index
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.'
      else
        render :edit
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :role)
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    def destroy
      current_user.invalidate_session!
      super
    end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/views/users/admin/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% present(user) do |user| %>
    <%  user.form = form %>
    <%= user.show_errors %>

    <%= user.input_row([ { attribute: :first_name },
                    { attribute: :last_name  } ]) %>

    <%= user.input_row([ { attribute: :role, kind: :select,
                      collection: user.roles,
                      selected: user.role,
                      blank: false } ]) %>

    <%= render  partial: 'shared/form_submit_bs',
                locals: { form: form } %>
  <% end %>
<% end %>

app/views/users/admin/edit.html.erb
<h1>Edit User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'List', list_users_path %>

app/views/users/admin/index.html.erb
<table class='table table-sm table-bordered table-hover'>
  <thead class='thead-light'>
    <tr>
      <th>Email</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
      <% present(u) do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.role %></td>
          <td><%= link_to 'Detail', show_user_path(user.id) %></td>
          <% if user.id != current_user.id %>
            <td><%= link_to 'Edit', edit_user_path(user.id) %></td>
            <td><%= link_to 'Destroy', user_registration_path(user.id), 
                            method: :delete, 
                            data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td>Current User</td>
            <td>Current User</td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/users/admin/show.html.erb
<h1>User Detail</h1>

<% present(@user) do |user| %>
	<%= user.notice(notice) %>

	<%= user.show(:email) %>
	<%= user.show(:first_name) %>
	<%= user.show(:last_name) %>
	<%= user.show(:role) %>
	<%= user.show(:approved) %>
	<%= user.show(:sign_in_count) %>
	<%= user.show(:current_sign_in_at) %>
	<%= user.show(:current_sign_in_ip) %>
	<%= user.show(:created_at) %>
<% end %>

<%= link_to 'List', list_users_path %>